name = "Lil Gator Game"
home = "https://discord.com/channels/731205301247803413/1084922067469734039"
default_url = "https://github.com/natronium/GatorArchipelago/releases/download/v{{version}}/lil_gator_game.apworld"
disabled = true # Doesn't load on 0.6.7

[versions]
"1.2.1" = {}
